# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc1c4aa854da90d4fd4417186fac06e01ad007a3b122c21732e51bffecf2b441f564cc0dff983bae56d6bbd2b1d997e8398665ea6c6406b85c8fd1ac4be50b70

test:
  secret_key_base: b87dfe5eeb4e4d8f69c4405294de4396e3ce6688819eefb36191d4631fdb0d9874c57458fe3b03068830028b2f3d55e4054bf7aad42520daf592576134d71ce6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
